In [1]:
from packaging import version
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
import tensorboard as tb
import os

from tensorboard.backend.event_processing import event_accumulator

In [5]:
def summarize_experiments(dataset, filter_path = "lightning_logs/new"):
    STORE_EVERYTHING_SIZE_GUIDANCE = {
        'COMPRESSED_HISTOGRAMS': 0,
        'IMAGES': 0,
        'AUDIO': 0,
        'SCALARS': 0,
        'HISTOGRAMS': 0,
        'TENSORS': 0,
    }

    filter_path = filter_path + "/" + dataset
    result = []
    for f in os.listdir(filter_path):
        ea = event_accumulator.EventAccumulator(filter_path + "/" + f, size_guidance = STORE_EVERYTHING_SIZE_GUIDANCE)
        ea.Reload()
        result.append(ea.Scalars("train/cumulative_error_step")[-1].value)
    result = np.array(result)
    return result.mean(), result.std(), result

In [55]:
summarize_experiments("german")

(283.75,
 21.558930864029413,
 array([267., 324., 262., 270., 305., 290., 275., 293., 282., 311., 289.,
        293., 338., 253., 275., 281., 259., 269., 267., 272.]))

In [56]:
print("german")#0.05
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-layers%3D6-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
          # http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-layers%3D6-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D2&format=csv
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()


german


(283.75,
 21.558930864029413,
 array([269., 262., 311., 324., 290., 270., 338., 259., 282., 253., 272.,
        305., 289., 267., 293., 281., 275., 267., 293., 275.]))

In [73]:
print("german")#0.001 + intercept
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-layers%3D6-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
          # http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-layers%3D6-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D2&format=csv
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()


german


(277.65,
 7.275128864838064,
 array([266., 283., 285., 273., 284., 270., 291., 286., 266., 283., 267.,
        278., 274., 271., 271., 282., 285., 278., 278., 282.]))

In [53]:
print("svmguide3")#0.05
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()


svmguide3


(292.7,
 4.1844951905815355,
 array([293., 296., 290., 291., 297., 293., 303., 291., 294., 291., 295.,
        294., 294., 299., 289., 290., 283., 292., 292., 287.]))

In [74]:
print("svmguide3")#0.05 + intercept
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()


svmguide3


(291.2,
 3.1559467676119,
 array([290., 291., 292., 292., 294., 292., 284., 292., 290., 292., 294.,
        295., 292., 295., 294., 290., 290., 292., 291., 282.]))

In [70]:
print("magic04")#0.001
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.01-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

magic04


(5460.55,
 302.9277925512944,
 array([5122., 5651., 5738., 5759., 5284., 5723., 5496., 5878., 5480.,
        5004., 5940., 5312., 5418., 5031., 5334., 5484., 5218., 5095.,
        6031., 5213.]))

In [62]:
print("magic04")#0.003
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.01-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

magic04


(6134.75,
 330.6089646394967,
 array([5836., 6264., 6082., 6253., 5881., 6708., 6007., 6558., 6064.,
        5805., 6944., 5909., 6065., 5654., 6111., 6231., 5882., 5788.,
        6602., 6051.]))

In [63]:
print("magic04")#0.0005
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.01-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

magic04


(6092.65,
 132.66735657274552,
 array([5968., 6307., 6086., 6223., 5990., 6112., 5962., 6340., 6187.,
        5934., 6345., 6036., 6123., 5923., 5975., 5966., 6044., 5999.,
        6196., 6137.]))

In [65]:
print("magic04")#0.001
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.01-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

magic04


(6070.05,
 234.0507370208434,
 array([5887., 6248., 6064., 6247., 5917., 6314., 5947., 6399., 6086.,
        5873., 6598., 5988., 6087., 5511., 5963., 5988., 5985., 5872.,
        6371., 6056.]))

In [67]:
print("a8a")
show_results()

a8a


(5719.7,
 84.88409745058257,
 array([5718., 5626., 5658., 5616., 5799., 5837., 5722., 5843., 5649.,
        5583., 5815., 5671., 5689., 5741., 5695., 5835., 5805., 5606.,
        5660., 5826.]))

In [78]:
print("a8a")#0.01
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.01-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

a8a


(5804.7,
 90.37538381661237,
 array([5830., 5711., 5784., 5643., 5891., 5931., 5813., 5891., 5714.,
        5725., 5922., 5786., 5714., 5829., 5761., 5963., 5812., 5734.,
        5705., 5935.]))

In [71]:
def show_results(dataset):
    vals = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0,1,2,3,4]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.05-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-missingness%3D{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p")
    print(results)    
show_results(None)

      average error  error std
p                             
0.01       316588.0        0.0
0.05       315659.0        0.0
0.10       313945.0        0.0
0.20       310320.0        0.0
0.30       306716.0        0.0
0.40       300404.0        0.0
0.50       295790.0        0.0
0.60       288643.0        0.0
0.70       280213.0        0.0
0.80       270755.0        0.0
0.90       261204.0        0.0
0.95       256961.0        0.0
0.99       253382.0        0.0


In [36]:
print("HIGGS")
show_results(None)

HIGGS
      average error  error std
p                             
0.01       470291.0        0.0
0.05       476204.0        0.0
0.10       472293.0        0.0
0.20       473606.0        0.0
0.30       476337.0        0.0
0.40       472141.0        0.0
0.50       465091.0        0.0
0.60       462509.0        0.0
0.70       467261.0        0.0
0.80       457393.0        0.0
0.90       453302.0        0.0
0.95       450284.0        0.0
0.99       449178.0        0.0


In [81]:
test = pd.read_csv(
    'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.05-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D4-missingness%3D0.4&format=csv'
)

In [82]:
test.head(1000)

Wall time    Step     Value
0    1.706810e+09    1132     485.0
1    1.706810e+09    5295    1782.0
2    1.706810e+09    5454    1819.0
3    1.706810e+09    5832    1916.0
4    1.706810e+09    5997    1967.0
..            ...     ...       ...
995  1.706846e+09  990883  259621.0
996  1.706847e+09  994960  260686.0
997  1.706847e+09  997501  261362.0
998  1.706847e+09  998351  261596.0
999  1.706847e+09  999999  262072.0

[1000 rows x 3 columns]

In [85]:
def show_results(dataset):
    vals = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0,1,2,3,4]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.05-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-missingness%3D{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p")
    print(results)    

In [79]:
show_results(None)

      average error   error std
p                              
0.01       439977.6  133.051268
0.05       440234.6  313.658158
0.10       439736.4  250.971393
0.20       438486.6  354.127435
0.30       435186.4  329.575849
0.40       432170.4  479.690567
0.50       427781.0  501.010978
0.60       423339.8  409.822108
0.70       418580.4  665.416742
0.80       412228.6  945.120648
0.90       405571.4  835.264892
0.95       398839.8  334.294122
0.99       391420.8  754.447453


In [86]:
show_results(None)

      average error    error std
p                               
0.01       284955.8    59.549643
0.05       283392.0   243.347488
0.10       280829.4   688.131557
0.20       274649.2   580.393453
0.30       269082.4   804.188436
0.40       262420.0   718.071863
0.50       256675.8   884.257745
0.60       250172.8  1085.640530
0.70       243775.6   892.670734
0.80       237120.0   805.492148
0.90       230180.0   769.257044
0.95       226248.4   469.163340
0.99       222396.6   244.433713


In [8]:
# def summarize_big_experiment(dataset, filter_path = "lightning_logs/new"):
#     # missingness = [0.01,0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99]
#     missingness = [0.8]
#     seeds = [0,1,2,3,4]
#     filter_path = filter_path + "/" + dataset
#     result = []
#     for m in missingness:
#         for f in os.listdir(filter_path):
#             if str("missingness=" + str(m)) in f:
#                 ea = event_accumulator.EventAccumulator(filter_path + "/" + f)
#                 ea.Reload()
#                 result.append(ea.Scalars("train/cumulative_error_step")[-1].value)
#     result = np.array(result)
#     return result.mean(), result.std()

In [9]:
# summarize_big_experiment("HIGGS")

DirectoryDeletedError: Directory lightning_logs/new/HIGGS/model=model.OnlineLearner-backbone=modules.Fast_AuxDrop_ODL-lr=0.05-width=50-loss=torch.nn.CrossEntropyLoss-seed=2-missingness=0.8 has been permanently deleted

In [111]:
def show_results():
    vals = [0.2,0.5,0.9,0.95]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0,1,2,3,4]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.AlphaExperiment-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.05-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-missingness%3D{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p")
    return results    

In [112]:
show_results()

average error   error std
p                              
0.20       274519.2  614.802212
0.50       256459.8  690.788361
0.90       229929.4  593.732802
0.95       226144.0  324.192535

In [113]:
def show_results():
    vals = [0.2,0.5,0.9,0.95]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0,1,2,3,4]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.VariableAlphaExperiment-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.05-width%3D50-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-missingness%3D{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p")
    return results    

In [114]:
show_results()

average error   error std
p                              
0.20       274649.2  580.393453
0.50       256675.8  884.257745
0.90       230180.0  769.257044
0.95       226248.4  469.163340

In [16]:
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
            f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D100-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std()

In [154]:
print("german")
show_results()

german


(318.15, 2.056088519495209)

In [155]:
print("svmguide3")
show_results()

svmguide3


(297.0, 0.9486832980505138)

In [163]:
print("magic04")
show_results()

magic04


(6674.7, 15.8590668073503)

In [162]:
print("a8a")
show_results()

a8a


(7843.45, 2.4591665254715878)

In [224]:
def show_results():
    widths = [10,25,50,100]
    layers=[1,2,3,4]
    blocks=[1,2,3,4]
    data = []
    row = []
    for width in widths:
        for layer in layers:
            for block in blocks:
                row = []
                for seed in np.arange(20):
                    row.append(pd.read_csv(
                        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D{width}-loss%3Dtorch.nn.CrossEntropyLoss-num_layers%3D{layer}-num_blocks%3D{block}-seed%3D{seed}&format=csv'
                    )['Value'].iloc[-1])
                data.append([block, layer, width, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["block", "layer", "width", "average error", "error std"])
    # results = results.set_index("p")
    return results    

In [213]:
german = show_results()
german

block  layer  width  average error  error std
0       1      1     10          316.0        0.0
1       2      1     10          316.0        0.0
2       3      1     10          316.0        0.0
3       4      1     10          327.0        0.0
4       1      2     10          316.0        0.0
..    ...    ...    ...            ...        ...
59      4      3    100          317.0        0.0
60      1      4    100          316.0        0.0
61      2      4    100          317.0        0.0
62      3      4    100          318.0        0.0
63      4      4    100          318.0        0.0

[64 rows x 5 columns]

In [214]:
# german.to_csv("german_hparams.csv")
german.sort_values(by='average error').head(10)

block  layer  width  average error  error std
19      4      1     25          315.0        0.0
0       1      1     10          316.0        0.0
28      1      4     25          316.0        0.0
32      1      1     50          316.0        0.0
34      3      1     50          316.0        0.0
35      4      1     50          316.0        0.0
36      1      2     50          316.0        0.0
37      2      2     50          316.0        0.0
38      3      2     50          316.0        0.0
39      4      2     50          316.0        0.0

In [215]:
german.sort_values(by='error std').head(10)

block  layer  width  average error  error std
0       1      1     10          316.0        0.0
34      3      1     50          316.0        0.0
35      4      1     50          316.0        0.0
36      1      2     50          316.0        0.0
37      2      2     50          316.0        0.0
38      3      2     50          316.0        0.0
39      4      2     50          316.0        0.0
40      1      3     50          316.0        0.0
41      2      3     50          316.0        0.0
42      3      3     50          316.0        0.0

In [219]:
for seed in list(np.arange(20)):
    print(pd.read_csv(f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.SetDecoder-lr%3D0.01-width%3D{10}-loss%3Dtorch.nn.CrossEntropyLoss-num_layers%3D{1}-num_blocks%3D{1}-seed%3D{seed}&format=csv'
                    )['Value'].iloc[-1])

6689.0
6690.0
6694.0
6688.0
6692.0
6684.0
6688.0
6688.0
6692.0
6687.0
6688.0
6690.0
6688.0
6670.0
6677.0
6678.0
6688.0
6684.0
6688.0
6727.0


In [225]:
magic = show_results()
magic

block  layer  width  average error  error std
0       1      1     10        6688.50  10.418733
1       2      1     10        6692.45  13.962360
2       3      1     10        6698.55  16.844806
3       4      1     10        6691.95  16.283350
4       1      2     10        6695.15  11.752766
..    ...    ...    ...            ...        ...
59      4      3    100        6691.70   5.831809
60      1      4    100        6691.50   4.260282
61      2      4    100        6691.45   4.758939
62      3      4    100        6694.75   6.684871
63      4      4    100        6693.95   7.228243

[64 rows x 5 columns]

In [226]:
magic.sort_values(by='average error').head(10)

block  layer  width  average error  error std
50      3      1    100        6638.65  11.697329
49      2      1    100        6638.85  10.928289
51      4      1    100        6639.85   8.217512
34      3      1     50        6641.55  11.293693
48      1      1    100        6641.65   9.483011
33      2      1     50        6644.45  11.951883
35      4      1     50        6644.75  11.268873
32      1      1     50        6646.10  14.969636
17      2      1     25        6659.20  16.506362
16      1      1     25        6660.50  17.086544

In [227]:
# magic.to_csv("magic_hparams.csv")

In [233]:
def show_results_ODL():
    widths = [15,25,50,100]
    layers=[4,5,6,7,8]
    data = []
    row = []
    for width in widths:
        for layer in layers:
            row = []
            for seed in np.arange(20):
                row.append(pd.read_csv(
                    f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineLearner-backbone%3Dmodules.Fast_AuxDrop_ODL-lr%3D0.1-width%3D{width}-layers%3D{layer}-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
                )['Value'].iloc[-1])
            data.append([layer, width, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["layer", "width", "average error", "error std"])
    # results = results.set_index("p")
    return results    

In [234]:
odl_german = show_results_ODL()
odl_german

layer  width  average error  error std
0       4     15         304.95  10.698014
1       5     15         301.45  14.420385
2       6     15         301.85   8.973712
3       7     15         305.75   8.172362
4       8     15         307.95   9.052486
5       4     25         308.35   9.535591
6       5     25         298.85   5.858967
7       6     25         302.30   6.221736
8       7     25         305.50   7.144928
9       8     25         307.35   6.612677
10      4     50         310.95   8.941337
11      5     50         306.85  11.641628
12      6     50         308.45   9.505130
13      7     50         307.35   9.398271
14      8     50         305.20   6.531462
15      4    100         317.25   4.145781
16      5    100         310.60   9.090655
17      6    100         308.25   8.123269
18      7    100         311.60   8.952095
19      8    100         312.20   8.524084

In [235]:
# german.to_csv("german_hparams.csv")
odl_german.sort_values(by='average error').head(10)

layer  width  average error  error std
6       5     25         298.85   5.858967
1       5     15         301.45  14.420385
2       6     15         301.85   8.973712
7       6     25         302.30   6.221736
0       4     15         304.95  10.698014
14      8     50         305.20   6.531462
8       7     25         305.50   7.144928
3       7     15         305.75   8.172362
11      5     50         306.85  11.641628
13      7     50         307.35   9.398271

In [106]:
## MLP

In [80]:
print("MLP german")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

MLP german


(313.0,
 19.964969321288727,
 array([309., 316., 321., 305., 298., 315., 326., 297., 298., 318., 314.,
        317., 300., 327., 304., 298., 388., 294., 298., 317.]))

In [81]:
print("MLP svm")
show_results()

MLP svm


(298.0,
 2.1908902300206643,
 array([296., 297., 298., 300., 296., 299., 298., 296., 299., 299., 297.,
        296., 301., 295., 297., 296., 304., 300., 296., 300.]))

In [88]:
print("MLP magic")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.0005-width%3D100-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

MLP magic


(6362.7,
 480.8614249448587,
 array([6612., 5918., 5977., 6122., 6491., 6110., 6761., 5970., 5865.,
        5894., 6348., 6693., 6501., 7997., 6693., 5946., 6675., 6119.,
        6131., 6431.]))

In [90]:
print("MLP a8a")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

MLP a8a


(5969.35,
 48.16770183432047,
 array([5947., 5973., 5963., 6011., 5895., 5948., 6007., 6034., 5996.,
        5879., 5952., 5980., 5922., 5927., 6020., 6004., 6067., 5903.,
        5954., 6005.]))

In [102]:
print("SUSY")
def show_results():
    vals = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0, 1, 2]:
            row.append(pd.read_csv(
                # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.0001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D2-p0.05&format=csv'
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.0001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-p{p_val}&format=csv'
                # f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMLP-backbone%3Dmodules.MLP-lr%3D0.0001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-p%3D{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p") 
    return results
show_results()   

SUSY


average error    error std
p                               
0.01  287647.333333   501.178833
0.05  287163.000000   676.825433
0.10  285962.333333   710.658067
0.20  283194.666667   713.653666
0.30  280480.333333   916.649818
0.40  276864.666667   883.204896
0.50  272788.000000   907.220297
0.60  267710.666667   913.696278
0.70  261558.666667   983.865280
0.80  253323.666667  1037.535970
0.90  241557.000000  1122.227547
0.95  234721.000000  1199.581038
0.99  228270.000000  1220.881922

In [105]:
print("HIGGS")
show_results()

HIGGS


average error   error std
p                              
0.01  450025.000000  280.643309
0.05  450456.666667  287.613552
0.10  451150.000000  179.901825
0.20  451894.333333   99.110488
0.30  451843.333333  248.978357
0.40  451736.666667  351.695260
0.50  451287.333333  225.355029
0.60  449713.666667  573.195914
0.70  447850.000000  656.917549
0.80  444418.000000  695.150343
0.90  440362.000000  422.616453
0.95  437508.666667  915.262561
0.99  434480.666667  676.466473

In [107]:
## Mixture

In [116]:
print("Mixture german")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

Mixture german


(277.1,
 11.962023240238251,
 array([263., 267., 289., 291., 280., 284., 300., 265., 265., 276., 271.,
        305., 269., 263., 267., 283., 277., 275., 268., 284.]))

In [118]:
print("Mixture svm")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

Mixture svm


(296.3,
 0.6403124237432849,
 array([296., 297., 297., 297., 296., 297., 296., 295., 297., 297., 296.,
        296., 296., 295., 297., 296., 296., 297., 296., 296.]))

In [122]:
print("Mixture magic")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.0005-width%3D100-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

Mixture magic


(5441.4,
 274.32396905848384,
 array([5122., 5710., 5678., 5713., 5284., 5646., 5508., 5824., 5442.,
        5023., 5910., 5297., 5454., 5026., 5355., 5443., 5205., 5096.,
        5855., 5237.]))

In [110]:
print("Mixture a8a")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

Mixture a8a


(5928.05,
 41.55294815052236,
 array([5947., 5909., 5883., 5950., 5852., 5941., 5956., 5983., 5963.,
        5854., 5931., 5943., 5864., 5904., 5944., 5971., 5974., 5874.,
        5938., 5980.]))

In [166]:
print("sum german")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

sum german


(287.25,
 6.94172168845741,
 array([285., 290., 286., 291., 294., 291., 302., 287., 287., 288., 274.,
        300., 295., 289., 280., 281., 281., 280., 279., 285.]))

In [168]:
print("sum svm")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

sum svm


HTTPError: HTTP Error 404: NOT FOUND

In [169]:
print("sum magic")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.0005-width%3D100-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

sum magic


(6278.15,
 497.39665006913754,
 array([6567., 5841., 5903., 6021., 6378., 5953., 6730., 5873., 5765.,
        5753., 6236., 6686., 6432., 7870., 6691., 5815., 6673., 5942.,
        6049., 6385.]))

In [170]:
print("sum a8a")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineMoE-backbone%3Dmodules.MLP-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

sum a8a


(5942.05,
 48.63895044097888,
 array([5967., 5956., 5885., 5949., 5838., 5953., 5998., 6011., 5955.,
        5899., 5920., 5963., 5881., 5907., 5989., 5988., 6021., 5877.,
        5913., 5971.]))

In [145]:
print("common backprop results")

common backprop results


In [171]:
print("german")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

german


(299.75,
 8.44911237941596,
 array([305., 307., 293., 290., 304., 312., 305., 296., 299., 308., 287.,
        307., 301., 311., 295., 292., 310., 281., 299., 293.]))

In [172]:
print("svm")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.001-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

svm


(298.45,
 3.3087006513131403,
 array([298., 297., 298., 300., 296., 298., 299., 296., 300., 299., 297.,
        296., 300., 295., 297., 296., 311., 300., 296., 300.]))

In [173]:
print("magic")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.0005-width%3D100-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

magic


(5536.65,
 100.76471356581132,
 array([5539., 5622., 5632., 5616., 5497., 5501., 5505., 5478., 5552.,
        5395., 5808., 5612., 5660., 5487., 5425., 5507., 5366., 5429.,
        5525., 5577.]))

In [174]:
print("a8a")
def show_results():
    data = []
    row = []
    row = []
    for seed in list(np.arange(20)):
        row.append(pd.read_csv(
        f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.01-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}&format=csv'
        )['Value'].iloc[-1])
    row = np.array(row)
    return row.mean(), row.std(), row
show_results()

a8a


(5691.6,
 40.71535336946003,
 array([5709., 5735., 5670., 5679., 5623., 5634., 5759., 5753., 5672.,
        5624., 5707., 5740., 5634., 5698., 5701., 5690., 5727., 5688.,
        5724., 5665.]))

In [159]:
print("SUSY")
def show_results():
    vals = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0, 1, 2]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.05-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-p{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p") 
    return results
show_results()   

SUSY


average error   error std
p                              
0.01  285258.000000   71.907348
0.05  283295.333333   49.378358
0.10  280050.000000  118.819190
0.20  274019.000000   41.085277
0.30  267954.000000   47.377913
0.40  261724.666667   39.718454
0.50  255032.000000   45.701933
0.60  248258.333333  101.686883
0.70  241336.666667   69.877671
0.80  234303.666667  108.321538
0.90  226514.666667  197.825400
0.95  222146.666667   56.981478
0.99  217394.666667  110.058570

In [160]:
print("HIGGS")
def show_results():
    vals = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]
    data = []
    row = []
    for p_val in vals:
        row = []
        for seed in [0, 1, 2]:
            row.append(pd.read_csv(
                f'http://127.0.0.1:6006/data/plugin/scalars/scalars?tag=train%2Fcumulative_error_step&run=model%3Dmodel.OnlineDelta-backbone%3Dmodules.StackofExperts-lr%3D0.05-width%3D250-layers%3D3-loss%3Dtorch.nn.CrossEntropyLoss-seed%3D{seed}-p{p_val}&format=csv'
            )['Value'].iloc[-1])
        data.append([p_val, np.array(row).mean(), np.array(row).std()])
    results = pd.DataFrame(data, columns=["p", "average error", "error std"])
    results = results.set_index("p") 
    return results
show_results()   

HIGGS


average error   error std
p                              
0.01  442795.666667  195.124462
0.05  442732.000000  150.481450
0.10  441958.666667   15.797327
0.20  439956.000000  147.352186
0.30  437475.000000   73.516438
0.40  434933.000000  332.628922
0.50  430324.666667  193.909486
0.60  425399.666667  178.447627
0.70  420455.666667  484.826659
0.80  411760.000000  106.210483
0.90  401437.666667  517.139783
0.95  394153.333333  565.184532
0.99  386681.333333  133.092282